# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                                                       |
# @ HubReworked                                         |
# @ Version: 1.1-SNAPSHOT                               |
# @ Reload or restart the server after making changes.  |
#                                                       |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# LaunchPad Settings
launchpad:
  enabled: true

  worlds:
    - world
    - world_nether
    - world_the_end

# Scoreboard Settings
sidebar:
  enabled: true

  features:
    title: "&e&l%world%"

    lines:
      - ""
      - "&lWaifuland"
      - ""
      - "&fUser: &5%player%"
      - "&fRank: %luckperms_prefix%"
      - "&fCash: &a$%vault_eco_balance_formatted%"
      - ""
      - "&fOnline: &a%online%"
      - ""
      - "&7/sidebar - hides sidebar"
      - ""

# TAB Settings
tab-customize:
  enabled: true

# Nametag Settings
nametag-customize:
  enabled: true