# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
#                                                       |
# @ HubReworked                                         |
# @ Version: 1.1-SNAPSHOT                               |
# @ Reload or restart the server after making changes.  |
#                                                       |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

#   Available built-in placeholders you can use in messages -
#   %player%    - Player's name
#   %world%     - Current world name
#   %gamemode%  - Player's game mode (e.g., SURVIVAL, CREATIVE)
#   %time%      - Current server time (HH:mm:ss)
#   %location%  - Player's location in "x, y, z" format
#   %x%         - Player's X coordinate (block)
#   %y%         - Player's Y coordinate (block)
#   %z%         - Player's Z coordinate (block)
#   %online%    - Number of online players on the server

# LaunchPad Settings
launchpad:
  enabled: true

  worlds:
    - world

# Scoreboard Settings
sidebar:
  enabled: true

  features:
    title: "&e&lHub Reworked"

    lines:
      - ""
      - "&l%world%"
      - ""
      - "&fUser: &5%player%"
      - "&fRank: %luckperms_prefix%"
      - "&fCash: &a$%vault_eco_balance_formatted%"
      - ""
      - "&fOnline: &a%online%"
      - ""
      - "&7/sidebar - Hides sidebar"
      - ""

# TAB Settings
tab-customize:
  enabled: true

# Nametag Settings
nametag-customize:
  enabled: true