name: HubReworked
version: 1.1-SNAPSHOT
main: me.makaioohara.hubreworked.HubReworked
api-version: 1.21
author: MakaioOhara
description: A reworked hub plugin for Minecraft 1.21 servers,

softdepend:
  - PlaceholderAPI

commands:
  hwreload:
    description: Reloads the HubReworked plugin configuration
    usage: /hwreload
    permission: hubreworked.reload
    permission-message: You do not have permission to reload HubReworked.
  sidebar:
    description: Toggles the sidebar scoreboard display
    usage: /sidebar
    permission: hubreworked.sidebar.toggle
    permission-message: You do not have permission to toggle the sidebar.

permissions:
  hubreworked.reload:
    description: Allows the player to reload the HubReworked plugin configuration
    default: op
  hubreworked.sidebar.toggle:
    description: Allows the player to toggle the sidebar scoreboard
    default: true
